### ISSUE TITLE
context not honored in xml2tex-conf//charmap/char

### ISSUE THREAD

**Issue by peppobon** [transpect/xml2tex#1]
Whit this example conf
`<char character="¯" string="${\thickspace\cup\thickspace}$" context="dbk:phrase[@css:font-familyzzzzzzzzzzzzzzz = 'MathematicalPi_4']"/>`

I get in the latex output the ${\thickspace\cup\thickspace}$ string and it should not, as the css:font-familyzzzzzzzzzzzzzzz attribute clearly does not exist in my source xml

regards
__peppo

**Comment by gimsieke** [comment]
Hi Peppo,

I investigated and I found out that the [schema](https://github.com/transpect/xml2tex/blob/f8755864ea6f72e400f6a12b570f0daf01cb408f/schema/xml2tex.rng#L188) in fact permits an optional `context` attribute for `char`. I investigated further and I found out that this attribute is currently not being evaluated. The replacement works globally and may not be constrained. I’ll investigate whether we can honour this constraint with the current approach. If it turns out to be too difficult or too inefficient, we’ll rather disallow the `context` attribute for the time being.

**Comment by gimsieke** [comment]
Please note that everything in the charmap (example: [docx2tex charmap](https://github.com/transpect/docx2tex/blob/master/conf/conf.xml#L367)) applies to text mode. [MathML to LaTeX translation](https://github.com/transpect/xml2tex/blob/a640999c434aad48f8979d1e2360ecb94ec00000/xpl/xml2tex.xpl#L195) happens before this charmap is applied.
So the general problem of handling character translations differently in math and text mode should be solved anyway.
Nevertheless, I fixed this issue by honouring the `@context` attribute on `char` entries. There is some documentation in the [schema](https://github.com/transpect/xml2tex/blob/aaa21d8861bf2d435cc544de5ec8076861a54f4d/schema/xml2tex.rng#L189).

**Comment by gimsieke** [comment]
Ah, I see. Your equations aren’t always MathML. Then this fix should help.

**Comment by gimsieke** [comment]
In the test case that you sent, you can use

```
<charmap>
    <char character="&#x3bc;" string="${\mu}$"/>
    <char character="&#x3bc;" string="\mu " context="dbk:mathphrase"/>
  </charmap>
```

I tried it, it works. 

Now we should update our sample configuration with `dbk:mathphrase` exceptions…
