### ISSUE TITLE
Error during calabash installation 

### ISSUE THREAD

**Issue by ewdlop** [transpect/xml2tex#3]
Hello,
I get this error when i run:
sudo calabash-frontend/calabash.sh -i source=xml2tex/example/example.xml -i conf=xml2tex/example/conf-hubcssa.xml xml2tex/xpl/xml2tex.xpl

ERROR: http://transpect.github.io/../index.html:1:107:Not a pipeline or library: html
ERROR: http://transpect.github.io/../index.html:1:107:Not a pipeline or library: html
ERROR: err:XS0044:Unexpected step name: tr:load
ERROR: It is a static error if any element in the XProc namespace or any step has element children other than those specified for it by this specification. In particular, the presence of atomic steps for which there is no visible declaration may raise this error.

How do i  resolve this? Thank you

**Comment by gimsieke** [comment]
Hi @ewdlop, thanks for reporting the issue. When I followed the instructions I hit a very similar issue, although not exactly the same:

```
$ calabash-frontend/calabash.sh -i source=xml2tex/example/example.xml -i conf=xml2tex/example/conf-hubcssa.xml xml2tex/xpl/xml2tex.xpl
ERROR: http://transpect.github.io/../index.html:1:107:Not a pipeline or library: html
ERROR: err:XS0044:Unexpected step name: tr:load-cascaded
ERROR: It is a static error if any element in the XProc namespace or any step has element children other than those specified for it by this specification. In particular, the presence of atomic steps for which there is no visible declaration may raise this error.
```

You already noticed that the Calabash repo would be cloned into calabash-frontend instead of calabash. I recently [updated the readme](https://github.com/transpect/xml2tex/commit/aa48ec0304ae5a3a2f56b64c93baf4a3430b0141) accordingly, so if you follow the instructions now, it will be cloned into calabash, and it will use the `saxon98` branch which contains some improvements.

The main issue that I was facing is that the [cascade](https://github.com/transpect/cascade) repo was missing, and also the corresponding XML catalog `nextCatalog` entry.

After I fixed that, as documented in the updated readme, the pipeline ran as expected.

Now you (or rather, the error message) reported that the `tr:load` step could not be found. This is because an XProc import statement `<p:import href="http://transpect.io/xproc-util/load/xpl/load.xpl"/>` did not succeed. I didn’t have a problem with this library. This probably happened because in your project, the XML catalog resolution was not set up correctly. 

`calabash.sh` uses an XML catalog that includes your project catalog at the location `xmlcatalog/catalog.xml`. Please make sure that you store the catalog given in the readme at this exact location. Also please take into account the recent changes that I made, i.e., also use the cascade library and its XML catalog.
